repos:
-   repo: https://github.com/timothycrosley/isort
    rev: 5.6.4
    hooks:
    -   id: isort
        stages: [commit]
-   repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
    -   id: black
        stages: [commit]
        language_version: python3.8
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.790
    hooks:
    -   id: mypy
        stages: [commit]
-   repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
    rev: v1.0.4
    hooks:
    -   id: python-bandit-vulnerability-check
        stages: [commit]
-   repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.1.3
    hooks:
    -   id: python-safety-dependencies-check
        stages: [commit]
-   repo: local
    hooks:
    -   id: flake8
        name: flake8
        stages: [commit]
        language: system
        entry: flake8
        types: [python]