repos:
-   repo: local
    rev: 5.6.4
    hooks:
    -   id: isort
        stages: [commit]
-   repo: local
    rev: 20.8b1
    hooks:
    -   id: black
        stages: [commit]
        language_version: python3.8
-   repo: local
    rev: 3.8.4
    hooks:
    -   id: flake8
        stages: [commit]
        additional_dependencies: [flake8-bugbear]
-   repo: local
    rev: v0.790
    hooks:
    -   id: mypy
        stages: [commit]
-   repo: local
    rev: v1.0.4
    hooks:
    -   id: python-bandit-vulnerability-check
        stages: [commit]
-   repo: local
    rev: v1.1.3
    hooks:
    -   id: python-safety-dependencies-check
        stages: [commit]
